flaskblog/blogs/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Blog, Tag
from flaskblog.blogs.forms import BlogForm
from flaskblog.utils import get_tags
from datetime import datetime

blogs = Blueprint('blogs', __name__)


@blogs.route("/blog/new", methods=['GET', 'POST'])
@login_required
def new_blog():
    form = BlogForm()
    if form.validate_on_submit():

        blogs = Blog.query.filter_by(user_id=current_user.id).all()

        blogged_today = []
        for blog in blogs:
            if datetime.utcnow().__str__()[:10] in blog.date_blogged.__str__():
                blogged_today.append(blog)

        if len(blogged_today) > 1:
            flash('You can only create two blogs per day!', 'danger')
        else:
            tags = [Tag(tag=tag) for tag in form.tags.data.split()]
            new_blog = Blog(subject=form.subject.data, description=form.description.data, bloggedBy=current_user, tag=tags)
            db.session.add(new_blog)
            db.session.commit()
            flash('Your blog has been created!', 'success')

        return redirect(url_for('main.home'))
    return render_template('create_blog.html', subject='New Blog', form=form, legend='New Blog')


@blogs.route("/blog/<int:blog_id>", methods=['GET', 'POST'])
def blog(blog_id):
    current_blog = Blog.query.get_or_404(blog_id)
    tags = get_tags(current_blog.tag)
    return render_template('blog.html',
                           subject=current_blog.subject,
                           blog=current_blog,
                           tags=tags,
                           comments=current_blog.comment)


@blogs.route("/blog/<int:blog_id>/update", methods=['GET', 'POST'])
@login_required
def update_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    if blog.bloggedBy != current_user:
        abort(403)
    form = BlogForm()
    if form.validate_on_submit():
        blog.subject = form.subject.data
        blog.description = form.description.data
        blog.tag = [Tag(tag=tag) for tag in form.tags.data.split()]
        db.session.commit()
        flash('Your blog has been updated!', 'success')
        return redirect(url_for('blogs.blog', blog_id=blog.blog_id))
    elif request.method == 'GET':
        form.subject.data = blog.subject
        tags = get_tags(blog.tag)
        form.tags.data = tags
        form.description.data = blog.description
    return render_template('create_blog.html', title='Update Blog', form=form, legend='Update Blog')


@blogs.route("/blog/<int:blog_id>/delete", methods=['POST'])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    if blog.bloggedBy != current_user:
        abort(403)
    db.session.delete(blog)
    db.session.commit()
    flash('Your blog has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/main/routes.py
from flask import render_template, request, Blueprint, flash
from flaskblog.models import User, Blog, Comment, follows
from flaskblog.utils import get_tags, get_tags_and_blog_ids
from flaskblog.main.forms import UsersForm
from flaskblog import db
import numpy as np

main = Blueprint('main', __name__)


@main.route("/")
# @main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    blogs = Blog.query.order_by(Blog.date_blogged.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', blogs=blogs)


@main.route("/about")
def about():
    return render_template('about.html', title="About")


@main.route('/initialize_db')
def initialize_db():
    page = request.args.get('page', 1, type=int)
    blogs = Blog.query.order_by(Blog.date_blogged.desc()).paginate(page=page, per_page=5)
    from flaskblog.scripts.db_scripts import db_init
    db_init()
    return render_template('home.html', blogs=blogs)


@main.route('/users_who_posted_at_least_two_blogs_with_different_tags')
def users_who_posted_at_least_two_blogs_with_different_tags():
    users = User.query.all()
    # print(users)

    users_with_two_or_more_blogs = []
    for user in users:
        if len(Blog.query.filter_by(user_id=user.id).all()) > 1:
            users_with_two_or_more_blogs.append(user)

    # Now I need to check the tags and see if the any tags in one blog are in the other tags
    for user in users_with_two_or_more_blogs:
        # getting all the blogs for a user
        blogs = Blog.query.filter_by(user_id=user.id)

        # then getting all the tags strings from all the blogs from that user in a list
        all_tags = []
        for blog in blogs:
            all_tags.append(get_tags(blog.tag))

        verified_users_who_posted_at_least_two_blogs_with_different_tags = []
        found = False
        # going through all tags strings
        for i, tagstring in enumerate(all_tags):
            # splitting
            tags = tagstring.split()
            for tag in tags:
                for j, other_tagstrings in enumerate(all_tags):
                    if i == j:
                        continue
                    else:
                        if tag in other_tagstrings:
                            break
                        else:
                            verified_users_who_posted_at_least_two_blogs_with_different_tags.append(user)
                            found = True
                            break
                if found:
                    break
            if found:
                break

    return render_template('users.html', users=verified_users_who_posted_at_least_two_blogs_with_different_tags, blogs=[])


@main.route('/blogs_of_a_user_with_all_positive_comments')
def blogs_of_a_user_with_all_positive_comments():

    users = User.query.all()

    users_with_blogs = []
    for user in users:
        if len(Blog.query.filter_by(user_id=user.id).all()) > 0:
            users_with_blogs.append(user)

    positive_blogs = []
    for user in users_with_blogs:
        blogs = Blog.query.filter_by(user_id=user.id)

        for blog in blogs:
            if len(Comment.query.filter_by(blog_id=blog.blog_id).all()) < 1:
                break
            else:
                comments = Comment.query.filter_by(blog_id=blog.blog_id)
                all_positive = True

            for comment in comments:
                if comment.sentiment != 'Positive':
                    all_positive = False
                    break

            if all_positive:
                positive_blogs.append(blog)

    return render_template('results.html', blogs=positive_blogs, users=[])


@main.route('/users_who_posted_the_most_blogs_on_feb_10th_2020')
def users_who_posted_the_most_blogs_on_feb_10th_2020():
    all_users = User.query.all()

    user_ids = [user.id for user in all_users]

    blogs = Blog.query.all()

    test_date = '2020-05-16'   # robin hood wins
    # test_date = '2020-05-13'  # tie between Rosa Parks, Robin Hood, Professor

    blogs_from_that_date = []

    for blog in blogs:
        if test_date.__str__()[:10] in blog.date_blogged.__str__():
            blogs_from_that_date.append(blog)

    counters = [0]*len(user_ids)

    for id in user_ids:
        for blog in blogs_from_that_date:
            if id == blog.bloggedBy.id:
                counters[id-1] += 1

    max_poster = np.argmax(counters)
    max_posts = max(counters)

    indeces = np.where(np.array(counters) >= max_posts)

    print(counters)
    print(indeces)

    try:
        users_who_posted_the_most = [all_users[int(i)] for i in indeces]
    except:
        users_who_posted_the_most = [all_users[int(i)] for i in indeces[0]]

    return render_template('users.html', users=users_who_posted_the_most, blogs=[])


@main.route('/users_followed_by_two_accounts_specified_by_user', methods=['GET', 'POST'])
def users_followed_by_two_accounts_specified_by_user():

    form = UsersForm()

    if form.validate_on_submit():

        user1 = form.user1.data
        user2 = form.user2.data

        User1 = User.query.filter_by(username=user1).first()
        User2 = User.query.filter_by(username=user2).first()

        if User1 is None:
            flash(f"{user1} is not in the database", "danger")

        elif User2 is None:
            flash(f"{user2} is not in the database", "danger")

        else:

            users_followed_by_user1 = db.session.query(follows).filter_by(follower_id=User1.id).all()
            users_followed_by_user2 = db.session.query(follows).filter_by(follower_id=User2.id).all()

            user_ids_followed_by_user1 = [user.user_id for user in users_followed_by_user1]
            user_ids_followed_by_user2 = [user.user_id for user in users_followed_by_user2]

            id_intersections = []
            for uid1 in user_ids_followed_by_user1:
                if uid1 in user_ids_followed_by_user2:
                    id_intersections.append(uid1)

            id_intersections = list(np.unique(id_intersections))

            users_followed_by_both = []
            for user_id in id_intersections:
                users_followed_by_both.append(User.query.filter_by(id=int(user_id)).first())

            return render_template('users.html', users=users_followed_by_both, blogs=[])

    return render_template('find_users_by_followers.html',
                           form=form,
                           legend='Find Users by Two Followers')


@main.route('/users_who_never_posted_a_blog')
def users_who_never_posted_a_blog():
    users = User.query.all()

    users_with_no_blogs = []
    for user in users:
        if len(Blog.query.filter_by(user_id=user.id).all()) < 1:
            users_with_no_blogs.append(user)

    return render_template('users.html', users=users_with_no_blogs, blogs=[])


@main.route('/users_who_never_posted_a_comment')
def users_who_never_posted_a_comment():
    all_users = User.query.all()

    users_with_no_comments = []

    for user in all_users:
        # grab all user's comments
        user_comments = user.comments

        # check if any users don't have any comments
        if len(user_comments) == 0:
            users_with_no_comments.append(user)

    return render_template('users.html', users=users_with_no_comments, blogs=[])


@main.route('/users_with_only_negative_comments')
def users_with_only_negative_comments():

    all_users = User.query.all()

    negative_users = []

    for user in all_users:
        # grab all user's comments
        user_comments = user.comments

        # check if any users don't have any comments
        if len(user_comments) == 0:
            continue

        # check to see if there's one positive comment
        all_negative = True
        for comment in user_comments:
            if comment.sentiment == 'Positive':
                all_negative = False
                break
            else:
                continue

        # if there isn't a single positive comment then we add that user to results
        if all_negative:
            negative_users.append(user)

    return render_template('users.html', users=negative_users, blogs=[])


@main.route('/users_whose_blogs_have_no_negative_comments')
def users_whose_blogs_have_no_negative_comments():

    users = User.query.all()

    users_with_blogs = []
    for user in users:
        if len(Blog.query.filter_by(user_id=user.id).all()) > 0:
            users_with_blogs.append(user)

    print(users_with_blogs)

    users_with_no_negative_comments = []
    for user in users_with_blogs:
        blogs = Blog.query.filter_by(user_id=user.id)

        for blog in blogs:

            comments = Comment.query.filter_by(blog_id=blog.blog_id)
            all_positive = True

            for comment in comments:
                if comment.sentiment != 'Positive':
                    all_positive = False
                    break

            if all_positive:
                users_with_no_negative_comments.append(user)
                break

    print(users_with_no_negative_comments)

    return render_template('users.html', users=users_with_no_negative_comments, blogs=[])


def user_pair_that_always_gave_positive_comments():

    all_users = User.query.all()
    pass

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Blog, Comment, Tag, follows
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.utils import get_tags

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    username=form.username.data,
                    email=form.email.data,
                    password=hashed_password
                    )
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created! You are now able to log in!", "success")
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_blogs(username):
    user = User.query.filter_by(username=username).first_or_404()
    blogs = user.blogs
    all_tags = [get_tags(blog.tag) for blog in blogs]
    blogs_and_tags = zip(blogs, all_tags)
    # print(blogs)
    return render_template('user_blogs.html', blogs=user.blogs, user=user, blogs_and_tags=blogs_and_tags)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated! You are now able to log in!", "success")
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/", methods=['POST', 'GET'])
@login_required
def follow():
    page = request.args.get('page', 1, type=int)
    follow_id = request.args.get('follow_id', 1, type=int)
    statement = follows.insert().values(user_id=current_user.id, follower_id=follow_id)
    db.session.execute(statement)
    db.session.commit()
    blogs = Blog.query.order_by(Blog.date_blogged.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', blogs=blogs)

flaskblog/templates/about.html
{% extends "layout.html"  %}
{% block content %}
    <h1>About Page</h1>
{% endblock content%}

flaskblog/templates/blog.html
{% extends "layout.html"  %}
{% block content %}
<article class="media content-section w-auto p-3">
    <article class="media content-section w-100 p-3">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + blog.bloggedBy.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_blogs', username=blog.bloggedBy.username) }}">{{ blog.bloggedBy.username }}</a>
                <small class="text-muted">{{ blog.date_blogged.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2 class="article-title">{{ blog.subject }}</h2>
            <p class="article-content">Tags: {{ tags }} </p>
            <p class="article-content">{{ blog.description }}</p>
            {% if blog.bloggedBy == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('blogs.update_blog', blog_id=blog.blog_id)}}">Update</a>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('comments.new_comment', blog_id=blog.blog_id)}}">Comment</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% else %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('comments.new_comment', blog_id=blog.blog_id)}}">Comment</a>
                </div>
            {% endif %}
        </div>
    </article>
</article>
{% for comment in comments %}
    <article class="media content-section w-auto p-3">
            <article class="media content-section w-100 p-3">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + comment.commentedBy.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('users.user_blogs', username=comment.commentedBy.username) }}">{{comment.commentedBy.username }}</a>
                        <small class="text-muted">{{ comment.date_commented.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <p class="text-justify">Sentiment: {{ comment.sentiment }}</p>
                    <p class="text-justify">{{ comment.comment }}</p>
                    {% if comment.commentedBy == current_user %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('comments.edit_comment', blog_id=blog.blog_id, comment_id=comment.comment_id)}}">Edit</a>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('comments.delete_comment', blog_id=blog.blog_id,  comment_id=comment.comment_id)}}">Delete</a>
                        </div>
                    {% endif %}
                </div>
            </article>
    </article>
{% endfor %}
<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete blog</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('blogs.delete_blog', blog_id=blog.blog_id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='main.css') }}>
        {% if title %}
            <title>EveryBlog - {{ title }}</title>
        {% else %}
            <title> EveryBlog</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">EveryBlog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
                            <form action="{{ url_for('search.search_by_tag') }}" method="GET">
                                <input class="ml-8 mr-8" type="text" name="tag">
                                <button class="ml-8 btn btn-light" type="submit">Search</button>
                            </form>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('blogs.new_blog') }}">New Blog</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages%}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}
                    {% endblock content%}
                </div>
                <div class="col-md-2">
                    <div class="content-section">
                        <h3>Database Controls</h3>
                        {% if current_user.is_authenticated %}
                            <p class="text-muted"> Click on these links to run queries and modify the database.
                                <ul class="list-group">
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.initialize_db')}}">Initialize Database</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_who_posted_at_least_two_blogs_with_different_tags')}}">Users Who Posted At Least Two Blogs with Different Tags</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.blogs_of_a_user_with_all_positive_comments')}}">List All Blogs of a User With All Positive Comments</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_who_posted_the_most_blogs_on_feb_10th_2020')}}">Users Who Posted the Most Blogs on 2/10/2020</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_followed_by_two_accounts_specified_by_user')}}">Users Followed By Two Accounts Specified By User</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_who_never_posted_a_blog')}}">All Users Who Never Posted a Blog</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_who_never_posted_a_comment')}}">All Users Who Never Posted a Comment</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_with_only_negative_comments')}}">Users With Only Negative Comments</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="{{ url_for('main.users_whose_blogs_have_no_negative_comments')}}">Users Whose Blogs Have No Negative Comments</a>
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        <a class="nav-item nav-link" href="#">A User Pair That Always Gave Positive Comments</a>
                                    </li>
                                </ul>
                            </p>
                        {% else %}
                            <p>Log in to use database controls.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </main>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

flaskblog/templates/results.html
{% extends "layout.html"  %}
{% block content %}
    {% for blog in blogs %}
        <article class="media content-section">
            <div class="media-body">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + blog.bloggedBy.image_file) }}">
                <div class="article-metadata pb-2 pt-2">
{#                    {% if current_user.following.blog.bloggedBy %}#}
                    <a class=" btn-secondary btn-sm mt-2 mb-1" href="{{ url_for('users.follow', blog_id=blog.blog_id)}}">Follow</a>
{#                    <a class=" btn-secondary btn-sm mt-2 mb-1" href="{{ url_for('users.unfollow', blog_id=blog.blog_id)}}">Follow</a>#}
                    <a class="mr-2" href="{{ url_for('users.user_blogs', username=blog.bloggedBy.username) }}">{{ blog.bloggedBy.username }}</a>
                    <small class="text-muted">{{ blog.date_blogged.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('blogs.blog', blog_id=blog.blog_id) }}">{{ blog.subject }}</a></h2>
{#                <p class="article-content">{{ tags }}</p>#}
                <p class="article-content">{{ blog.description }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content%}

flaskblog/templates/users.html
{% extends "layout.html"  %}
{% block content %}
    {% for user in users %}
        <article class="media content-section">
            <div class="media-body">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
                <div class="article-metadata pb-2 pt-2">
                    <a class="btn-secondary btn-sm mt-2 mb-1" href="{{ url_for('users.follow', follow_id=user.id)}}">Follow</a>
                    <a class="mr-2" href="{{ url_for('users.user_blogs', username=user.username) }}">{{ user.username }}</a>
                </div>
            </div>
        </article>
    {% endfor %}
{% endblock content%}